name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: stupid find
        id: jar
        run: |
          JAR=$(find build/libs -maxdepth 1 -type f -name '*.jar' ! -name '*-sources.jar')
          echo "path=$JAR" >> "$GITHUB_OUTPUT"
      - name: capture jar
        uses: actions/upload-artifact@v7
        with:
          path: ${{ steps.jar.outputs.path }}
          archive: false